name: Generate and Push Python SDK

on:
  push:
    branches:
      - main

jobs:
  generate_and_push_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest

      - name: Set Git Config
        run: |
          git config --local user.email "dprakash2101@gmail.com"
          git config --local user.name "dprakash2101"

      - name: Generate Python SDK
        run: |
          set -e
          openapi-generator-cli generate --verbose -i Ingrammicroreseller-api.yaml -g python -o ${{ github.workspace }}/python --package-name IngramMicroresellerPythonSDK

      - name: Commit and Push generated Python SDK
        run: |
          cd ${{ github.workspace }}/python

          if [ -n "$(git status --porcelain)" ]; then
            # Check if the remote already exists
            if ! git remote | grep -q "origin_with_token"; then
              git remote add origin_with_token https://dprakash2101:github.com/im-deviprakash/PythonSDK.git
            fi

            # Use the same branch name for push as the newly created branch
            new_branch_name="feature-branch-python-$(date +'%Y%m%d%H%M%S')"
            git checkout -b $new_branch_name
            git add --all
            git commit -m "Add generated Python SDK"
            git push --force origin_with_token $new_branch_name
          else
            echo "No changes to commit."
          fi
